language: generic

os:
  - linux

sudo: true

dist: xenial

compiler:
  - gcc
  - clang

env:
  global:
    - ROS_REPO=ros
    - ROS_DISTRO=dashing
  matrix:
    - ROS_REPO=ros
    - ROS_DISTRO=dashing

script:
  - . ci_travis.sh
